version: "3"

services:
  node:
    image: ultra_game_api
    networks:
      app_net:
    build:
      context: ./game-api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

networks:
  app_net:
