GET http://localhost:3000/game HTTP/1.1

###

GET http://localhost:3000/game/5dd6efda-d6e9-44ef-8d41-52d4af38f3d8 HTTP/1.1

###

GET http://localhost:3000/game/54b5da69-68d4-4a2e-809f-6a9729139d9f/publisher HTTP/1.1

###

GET http://localhost:3000/game/update-listing HTTP/1.1

###

POST http://localhost:3000/game HTTP/1.1
Content-Type: application/json

{
  "title": "New game",
  "price": 19.99,
  "publisherId": "publisherIdSample",
  "tags": ["movie", "action"],
  "releaseDate": "2020-09-07T16:43:57.272Z"
}

###

PATCH http://localhost:3000/game/79e50d1d-58f7-4d3e-9e89-695cd4d6d5fd HTTP/1.1
Content-Type: application/json

{
  "title": "New game"
}

###

DELETE http://localhost:3000/game/5c7ce380-924b-443f-8fb5-b2e4c8f13a19 HTTP/1.1

